### ISSUE TITLE
README config example typo: "autowiring" should be "autowire"

### ISSUE THREAD

**Issue by gmpf** [terminal42/service-annotation-bundle#1]
There's a typo in the "Using autowiring…" section of the README. It says
```
autowiring: true
```
as opposed to
```
autowire: true
```
I copy-pasted the example and Symfony yelled at me in its signature style. ;)

> In FileLoader.php line 166:
> The configuration key "autowiring" cannot be used to define a default value in "[…]/config/services.yml". Allowed keys are "public", "tags", "autowire", "autoconfigure", "bind" in "[…]/config/services.yml" (which is  being imported from "[…]/config/config.yml").

**Comment by aschempp** [comment]
Thanks for pointing this out!
