### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by ausi** [terminal42/service-annotation-bundle#5]
The current version is not compatible with PHP 8.

**Comment by aschempp** [comment]
Do you mean composer says so or there is an issue in the code?

**Comment by ausi** [comment]
Composer says so ☺️

**Comment by aschempp** [comment]
Fixed in https://github.com/terminal42/service-annotation-bundle/commit/6676feaff9ae1efcb261b463d82f42d2fe1fc67a
